<<<<<<< HEAD
# Generated by Django 2.2.6 on 2019-10-09 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 2.2.6 on 2019-10-10 22:08

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 318f7ba2de846503cfd84d1339d1bd0619a6e2a9


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('material', '0004_remove_material_cantidad'),
=======
        ('material', '__first__'),
>>>>>>> 318f7ba2de846503cfd84d1339d1bd0619a6e2a9
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
<<<<<<< HEAD
                ('status', models.BooleanField(default=True)),
                ('fechaMod', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Material',
=======
            ],
        ),
        migrations.CreateModel(
            name='InventarioMaterial',
>>>>>>> 318f7ba2de846503cfd84d1339d1bd0619a6e2a9
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='materiales',
<<<<<<< HEAD
            field=models.ManyToManyField(through='inventario.Inventario_Material', to='material.Material'),
=======
            field=models.ManyToManyField(through='inventario.InventarioMaterial', to='material.Material'),
>>>>>>> 318f7ba2de846503cfd84d1339d1bd0619a6e2a9
        ),
    ]
