# Generated by Django 2.2.6 on 2019-10-23 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 15, 54, 42, 334497, tzinfo=utc)),
        ),
    ]
