# Generated by Django 2.2.6 on 2019-10-09 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20191009_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fechaMod',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 17, 41, 4, 609933, tzinfo=utc)),
        ),
    ]
