# Generated by Django 2.2.6 on 2019-10-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_remove_revision_inventario'),
        ('inventario', '0002_auto_20191021_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomaterial',
            name='fecha',
        ),
        migrations.AddField(
            model_name='inventariomaterial',
            name='revision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='revision.Revision'),
            preserve_default=False,
        ),
    ]
