# Generated by Django 2.2.6 on 2019-10-22 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20191022_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomaterial',
            name='revision',
        ),
        migrations.AddField(
            model_name='inventariomaterial',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
