# Generated by Django 2.2.6 on 2019-10-22 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('fecha_mod', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
