# Generated by Django 2.2.6 on 2019-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20191003_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
