# Generated by Django 2.2.6 on 2019-10-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cantidad',
        ),
    ]
