# Generated by Django 2.2.6 on 2019-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='turno',
            field=models.IntegerField(choices=[(5, 'NocturnoViernes'), (1, 'DiurnoSabado'), (2, 'NocturnoSabado'), (3, 'DiurnoDomingo'), (4, 'NocturnoDomingo')], default=None, max_length=50, null=True),
        ),
    ]
