# Generated by Django 2.2.6 on 2019-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Nocturno Viernes'), (2, 'Diurno Sábado'), (3, 'Nocturno Sábado'), (4, 'Diurno Domingo'), (5, 'Nocturno Domingo')], default=None, null=True),
        ),
    ]
