# Generated by Django 2.2.6 on 2019-10-21 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 10, 21, 15, 28, 8, 435631, tzinfo=utc))),
                ('inventario_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.InventarioMaterial')),
            ],
        ),
    ]
