# Generated by Django 2.2.6 on 2019-10-21 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 16, 3, 48, 928963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revision',
            name='inventario_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario'),
        ),
    ]
