# Generated by Django 2.2.6 on 2019-10-22 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 18, 24, 58, 829948, tzinfo=utc)),
        ),
    ]
