# Generated by Django 2.2.6 on 2019-10-21 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_auto_20191021_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='inventario_material',
            new_name='inventario',
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 16, 6, 59, 72441, tzinfo=utc)),
        ),
    ]
