# Generated by Django 2.2.6 on 2019-10-21 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_auto_20191021_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
