# Generated by Django 2.2.6 on 2019-10-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_auto_20191021_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='inventario',
        ),
    ]
