# Generated by Django 2.2.6 on 2019-10-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20191022_1838'),
        ('revision', '0005_remove_revision_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario'),
            preserve_default=False,
        ),
    ]
