# Generated by Django 2.2.6 on 2019-10-23 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ambulancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancia',
            name='fecha_mod',
            field=models.DateField(default=datetime.datetime(2019, 10, 23, 16, 15, 41, 435876, tzinfo=utc)),
        ),
    ]
